---
title: "Publications"
description: "Research publications and scholarly output"
---

## Peer-Reviewed Journal Articles

### 2025

**Quillivic, R.**, Auxéméry, Y., Gayraud, F., Dayan, J., & Mesmoudi, S. (2025). Linguistic markers for identifying post‑traumatic stress disorder and associated symptoms: a systematic literature review. *Journal of the American Medical Informatics Association*. [{{< ai doi >}}](https://doi.org/10.1093/jamia/ocaf075) [{{< fa code >}}](https://github.com/psycholinguistics2125/systematic_review)

### 2024

**Quillivic, R.**, Gayraud, F., Auxéméry, Y., et al. (2024). Interdisciplinary approach to identify language markers for PTSD using machine and deep learning. *Scientific Reports*, 14, 11206. [{{< ai doi >}}](https://www.nature.com/articles/s41598-024-61557-7) [{{< fa code >}}](https://github.com/psycholinguistics2125/linguistic_code_of_ptsd)

## Conference Papers and Presentations

### 2025

**Quillivic, R.**, Fradkin, I. (2025, July). *Characterizing the Paradoxical Interplay of Semantic Perseveration and Incoherence in Psychiatry using Theory‑Driven Generative Language Simulations*. **Poster accepted**, Computational Psychiatry Conference (CPC 2025). [{{< fa file-powerpoint >}}](https://docs.google.com/presentation/d/1SXxAujxuF_1e5_BpiA_D4LrQcB1OVbbZZe5zMHw4m2c/edit?usp=sharing)

### 2024

Boccara, S., Mesmoudi, S., Dayan, J., & **Quillivic, R.** (2024, June). *Quantization of speech disorganization for PTSD and speech disorders detection*. **JADT 2024, LesLa**. [{{< ai hal >}}](https://hal.science/hal-04627800) [{{< fa code >}}](https://github.com/NLP-for-Psycholinguistic/text_coherence_pipeline)

**Quillivic, R.**, Payet, C. (2024, June). *Semi‑Structured Interview Analysis: A French NLP Approach for Social Sciences*. **JADT 2024, LesLa**. [{{< ai hal >}}](https://hal.science/hal-04627806) [{{< fa code >}}](https://github.com/psycholinguistics2125/ssi-toolbox-fr)

### 2023

**Quillivic, R.**, Mesmoudi, S. (2023). *La culture du logiciel libre suffit-elle à faire de l'IA un commun ?* **Journées Scientifiques de Rochebrune**, France. [{{< ai hal >}}](https://hal.science/hal-04534042v1)

### 2019

Lopez, I., **Quillivic, R.**, Evans, H., & Arriaga, R.I. (2019). *Denouncing Sexual Violence: A Cross-Language and Cross-Cultural Analysis of #MeToo and #BalanceTonPorc*. **Proceedings of the 17th IFIP Conference on Human-Computer Interaction (INTERACT)**. [{{< ai hal >}}](https://inria.hal.science/hal-02544580/document) [{{< fa code >}}](https://github.com/binbin83/metoo_project)

## Preprints and Papers Under Review

### Under Review

Mimault, T.*, **Quillivic, R.***  et al. *A linguistic study of the traumatic discourse used by intimate partner violence perpetrators: a pilot study*. **Under review** at *Journal of Psychiatric Research*. [{{< fa code >}}](https://github.com/psycholinguistics2125/violent_men)

**Quillivic, R.**, Dolan, R. J., & Fradkin, I. (2025). *Characterizing the Paradoxical Interplay of Semantic Perseveration and Incoherence in Psychiatry using Theory‑Driven Generative Language Simulations*. **Under review** at *Schizophrenia Bulletin*. [{{< ai hal >}}](https://hal.science/hal-05086512) [{{< fa code >}}](https://github.com/psycholinguistics2125/paraphrase_detection)

### Preprints

**Quillivic, R.**, et al. (2024). *Figures of Speech as a Linguistic Marker of Post‑Traumatic Stress Disorder*. [{{< ai hal >}}](https://hal.science/hal-05088954)

## Book Chapters

**Quillivic, R.** (2025). Contributing author, *Psychiatrie & Psychologie du futur*. **Éditions Ellipses**. [{{< fa book >}}](https://www.editions-ellipses.fr/accueil/16036-psychiatrie-psychologie-du-futur-9782340105959.html)

*Note: Presented at Académie Nationale de Médecine, June 2025*

## Invited Talks

**Quillivic, R.** (2024). *Exploration du lien entre le discours et le TSPT*. **Programme 13-Novembre seminar**, Université Paris 1. [{{< fa video >}}](https://www.youtube.com/watch?v=l9kvqLFBqNY)

## Thesis

**Quillivic, R.** (2024). *Construction de profils psycholinguistiques pour le Trouble de Stress Post-Traumatique à l'aide du TALN*. **Ph.D. thesis**, École Pratique des Hautes Études (EPHE, PSL). [{{< fa file-text >}}](https://theses.fr/2024UPSLP082) [{{< fa file-powerpoint >}}](https://docs.google.com/presentation/d/1Gqe2Ott-h4TNdc6gnR7U5-8WFqxtymScf_EeHsAekgw/edit?usp=sharing)

*Supervisors*: Dr. Salma Mesmoudi, Prof. Jacques Dayan  
*Defended*: December 20, 2024

## Service to the Profession

### Journal Review

- **BJPsych Open** (October 2024)
- **Annales Médico-Psychologiques** (May 2024)

### Editorial Activity

Regular reviewer for journals in computational psychiatry and natural language processing.

---

*{{< fa asterisk >}} indicates equal contribution*

## Research Metrics

- **ORCID**: [0000-0009-9372-0173](https://orcid.org/0000-0009-9372-0173)
- **Google Scholar**: [Profile](https://scholar.google.com/citations?user=your-id)
- **HAL**: [Publications](https://hal.science/search/index/q/*/authFullName_s/Robin+Quillivic)
